# Generated by Django 5.2.9 on 2026-01-27 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='نام هنرمند')),
                ('bio', models.TextField(blank=True, default='', verbose_name='بیوگرافی')),
            ],
            options={
                'verbose_name': 'هنرمند',
                'verbose_name_plural': 'هنرمندان',
            },
        ),
        migrations.CreateModel(
            name='ArtworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع اثر هنری')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع اثر هنری',
                'verbose_name_plural': 'انواع اثر هنری',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, editable=False, max_length=5, unique=True)),
                ('title', models.CharField(max_length=30, verbose_name='عنوان اثر')),
                ('authenticity_status', models.IntegerField(choices=[(0, 'اصالت تایید شده'), (1, 'اصالت تایید نشده')], default=0, verbose_name='وضعیت اصالت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('is_sold', models.BooleanField(default=False, verbose_name='فروخته شده')),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True, verbose_name='ابعاد')),
                ('creation_year', models.IntegerField(blank=True, null=True, verbose_name='سال خلق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('provenance', models.TextField(blank=True, verbose_name='پیشینه')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='store.artist', verbose_name='هنرمند')),
            ],
            options={
                'verbose_name': 'اثر هنری',
                'verbose_name_plural': 'آثار هنری',
            },
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان بازدید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.artwork', verbose_name='اثر هنری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه بازدید',
                'verbose_name_plural': 'تاریخچه\u200cهای بازدید',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پسندیدن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.artwork', verbose_name='اثر هنری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پسند',
                'verbose_name_plural': 'پسندها',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
