# Generated by Django 5.2.9 on 2026-05-07 20:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='نام هنرمند')),
                ('bio', models.TextField(blank=True, default='', verbose_name='بیوگرافی')),
            ],
            options={
                'verbose_name': 'هنرمند',
                'verbose_name_plural': 'هنرمندان',
            },
        ),
        migrations.CreateModel(
            name='ArtworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع اثر هنری')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نوع اثر هنری',
                'verbose_name_plural': 'انواع اثر هنری',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, editable=False, max_length=5, unique=True)),
                ('title', models.CharField(max_length=30, verbose_name='عنوان اثر')),
                ('authenticity_status', models.IntegerField(choices=[(0, 'اصالت تایید شده'), (1, 'اصالت تایید نشده')], default=0, verbose_name='وضعیت اصالت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('is_sold', models.IntegerField(choices=[(0, 'موجود'), (1, 'فروخته شده'), (2, 'رزرو شده')], default=0, verbose_name='وضعیت فروش')),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True, verbose_name='ابعاد')),
                ('creation_year', models.IntegerField(blank=True, null=True, verbose_name='سال خلق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('provenance', models.TextField(blank=True, verbose_name='پیشینه')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='store.artist', verbose_name='هنرمند')),
                ('artwork_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='store.artworktype', verbose_name='نوع اثر هنری')),
            ],
            options={
                'verbose_name': 'اثر هنری',
                'verbose_name_plural': 'آثار هنری',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان خرید')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_histories', to='store.artwork', verbose_name='اثر هنری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه خرید',
                'verbose_name_plural': 'تاریخچه خریدها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='شناسه نشست (Session)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ورود')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین فعالیت')),
                ('is_closed', models.BooleanField(default=False, verbose_name='پایان یافته')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر (در صورت لاگین)')),
            ],
            options={
                'verbose_name': 'لاگ حضور در سایت',
                'verbose_name_plural': 'لاگ\u200cهای حضور در سایت',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='TelegramPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی چت تلگرام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید کاربر'), ('confirmed', 'تایید شده (نیاز به تماس)'), ('rejected', 'لغو شده توسط کاربر'), ('contacted', 'تماس گرفته شد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_requests', to='store.artwork', verbose_name='اثر هنری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست خرید تلگرامی',
                'verbose_name_plural': 'درخواست\u200cهای خرید تلگرامی',
            },
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان بازدید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.artwork', verbose_name='اثر هنری')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه بازدید',
                'verbose_name_plural': 'تاریخچه\u200cهای بازدید',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پسندیدن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.artwork', verbose_name='اثر هنری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پسند',
                'verbose_name_plural': 'پسندها',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
