# Generated by Django 5.2.9 on 2026-02-07 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_artwork_artwork_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی چت تلگرام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید کاربر'), ('confirmed', 'تایید شده (نیاز به تماس)'), ('rejected', 'لغو شده توسط کاربر'), ('contacted', 'تماس گرفته شد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.artwork', verbose_name='اثر هنری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست خرید تلگرامی',
                'verbose_name_plural': 'درخواست\u200cهای خرید تلگرامی',
            },
        ),
    ]
