# Generated by Django 5.2.9 on 2026-02-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_telegrampurchaserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='is_sold',
            field=models.IntegerField(choices=[(0, 'موجود'), (1, 'فروخته شده'), (2, 'رزرو شده')], default=0, verbose_name='وضعیت فروش'),
        ),
    ]
