# Generated by Django 5.2.9 on 2026-02-15 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_artwork_is_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('purchase_request_created', 'ثبت درخواست خرید'), ('purchase_request_confirmed', 'تایید درخواست خرید'), ('purchase_request_rejected', 'لغو درخواست خرید'), ('purchase_request_contacted', 'تماس گرفته شد')], max_length=50, verbose_name='رویداد')),
                ('price_snapshot', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت در زمان ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.artwork', verbose_name='اثر هنری')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='store.telegrampurchaserequest', verbose_name='درخواست خرید تلگرامی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه خرید',
                'verbose_name_plural': 'تاریخچه خریدها',
                'ordering': ['-created_at'],
            },
        ),
    ]
