# Generated by Django 5.2.9 on 2026-02-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_purchasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='price_snapshot',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='purchase_request',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='artwork_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام اثر خریداری شده'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره موبایل خریدار'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='product_id',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='پروداکت ایدی محصول خریداری شده'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان خرید'),
        ),
    ]
