# Generated by Django 5.2.9 on 2026-03-15 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_purchasehistory_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_histories', to='store.artwork', verbose_name='اثر هنری'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='telegrampurchaserequest',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_requests', to='store.artwork', verbose_name='اثر هنری'),
        ),
        migrations.AlterField(
            model_name='telegrampurchaserequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
