# Generated by Django 5.2.9 on 2026-03-26 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_purchasehistory_artwork_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sales', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده (ادمین)'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری پرداخت'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='purchased_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت در لحظه خرید'),
        ),
        migrations.CreateModel(
            name='SiteVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='شناسه نشست (Session)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ورود')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین فعالیت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر (در صورت لاگین)')),
            ],
            options={
                'verbose_name': 'لاگ حضور در سایت',
                'verbose_name_plural': 'لاگ\u200cهای حضور در سایت',
                'ordering': ['-last_activity'],
            },
        ),
    ]
