# Generated by Django 5.2.9 on 2026-03-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_purchasehistory_confirmed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='artwork_title',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='buyer_phone',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='purchased_price',
        ),
    ]
