# Generated by Django 5.2.9 on 2026-04-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_visithistory_ip_address_alter_visithistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitlog',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='پایان یافته'),
        ),
        migrations.AlterField(
            model_name='sitevisitlog',
            name='session_key',
            field=models.CharField(max_length=40, verbose_name='شناسه نشست (Session)'),
        ),
    ]
