# Generated by Django 6.0 on 2026-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_sitevisitlog_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
