# Generated by Django 6.0 on 2026-05-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_telegrampurchaserequest_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام متریال')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'متریال',
                'verbose_name_plural': 'متریال\u200cها',
                'db_table': 'store_material',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام موضوع')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوعات',
                'db_table': 'store_subject',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربرد')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'کاربرد',
                'verbose_name_plural': 'کاربردها',
                'db_table': 'store_usage',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='store.material', verbose_name='متریال'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='store.subject', verbose_name='موضوع'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='store.usage', verbose_name='کاربرد'),
        ),
    ]
