# Generated by Django 6.0 on 2026-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_material_subject_usage_artwork_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات قیمت'),
        ),
    ]
