# Generated by Django 5.2.9 on 2026-05-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_artwork_price_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='توضیحات'),
        ),
    ]
