# Generated by Django 5.2.9 on 2026-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworktype',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='توضیحات'),
        ),
    ]
