# Generated by Django 5.2.9 on 2026-09-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_artworktype_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitevisitlog",
            name="operating_system",
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="سیستم عامل"),
        ),
    ]
