# Generated by Django 5.2.9 on 2026-01-27 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='عملیات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش فعالیت',
                'verbose_name_plural': 'گزارش\u200cهای فعالیت',
                'ordering': ['-timestamp'],
            },
        ),
    ]
