# Generated by Django 5.2.9 on 2026-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_adminactivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('ban', 'Ban'), ('unban', 'Unban')], max_length=1000),
        ),
    ]
