# Generated by Django 6.0 on 2026-09-01 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_alter_adminactivitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactivitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'لاگ فعالیت ادمین', 'verbose_name_plural': 'لاگ\u200cهای فعالیت ادمین\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='adminactivitylog',
            name='core_admina_content_de0e0a_idx',
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='description',
            field=models.TextField(blank=True, verbose_name='شرح عملیات'),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='target_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه هدف'),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='target_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدف'),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='target_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع هدف'),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='نوع عملیات'),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مدیر'),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='تغییرات'),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع مدل'),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه عددی مدل'),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action', 'timestamp'], name='core_admina_action_2d449f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['target_type', 'timestamp'], name='core_admina_target__44ba0a_idx'),
        ),
    ]
