# Generated by Django 5.2.9 on 2026-01-27 20:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, editable=False, max_length=5, unique=True)),
                ('title', models.CharField(max_length=30, verbose_name='عنوان اثر')),
                ('authenticity_status', models.IntegerField(choices=[(0, 'اصالت تایید شده'), (1, 'اصالت تایید نشده')], default=0, verbose_name='وضعیت اصالت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('medium', models.CharField(blank=True, max_length=255, verbose_name='تکنیک')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('is_sold', models.BooleanField(default=False, verbose_name='فروخته شده')),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True, verbose_name='ابعاد')),
                ('creation_year', models.IntegerField(blank=True, null=True, verbose_name='سال خلق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت پایه')),
                ('current_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت فعلی')),
                ('min_bid_percentage', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='حداقل درصد افزایش پیشنهاد')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('bid_type', models.CharField(choices=[('PERCENTAGE', 'درصدی'), ('FIXED', 'مبلغ ثابت')], default='PERCENTAGE', max_length=10, verbose_name='نوع افزایش پیشنهاد')),
                ('min_bid_fixed_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حداقل مبلغ افزایش (ثابت)')),
                ('provenance', models.TextField(blank=True, verbose_name='پیشینه')),
                ('condition_report', models.TextField(blank=True, verbose_name='گزارش وضعیت')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='store.artist', verbose_name='هنرمند')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL, verbose_name='برنده')),
            ],
            options={
                'verbose_name': 'مزایده',
                'verbose_name_plural': 'مزایده\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auction', verbose_name='مزایده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشنهاد',
                'verbose_name_plural': 'پیشنهادها',
                'ordering': ['-created_at'],
            },
        ),
    ]
