# Generated by Django 5.2.9 on 2026-05-07 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('products_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'db_table': 'auction_auction',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('authenticity_status', models.SmallIntegerField(choices=[(0, 'اصالت تایید شده'), (1, 'اصالت تایید نشده')], default=0, verbose_name='وضعیت اصالت')),
                ('description', models.TextField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bid_criteria', models.SmallIntegerField(choices=[(0, 'percentage-based'), (1, 'fixed-amount')], default=0)),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_products', to='store.artist')),
                ('artwork_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_products', to='store.artworktype')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='auction.auction')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auction_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionVisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان بازدید')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to='auction.auction', verbose_name='مزایده')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to='auction.auctionproduct', verbose_name='محصول مزایده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_visit_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه بازدید مزایده',
                'verbose_name_plural': 'تاریخچه بازدیدهای مزایده',
                'db_table': 'auction_visit_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user_fullname', models.CharField(max_length=255)),
                ('user_mobile', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionproduct', to_field='product_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auction_bid',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user_fullname', models.CharField(max_length=255)),
                ('user_mobile', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_prices', to='auction.auction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_prices', to='auction.auctionproduct', to_field='product_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auction_suggested_price',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('outbid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='auction.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='auction.auctionproduct', to_field='product_id')),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='auction.bid')),
            ],
            options={
                'db_table': 'auction_cart_item',
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='uniq_auction_cart_item_user_product')],
            },
        ),
    ]
