# Generated by Django 5.2.9 on 2026-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_add_created_at_to_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='authenticity_status',
            field=models.SmallIntegerField(choices=[(0, 'اصالت تایید شده'), (1, 'اصالت تایید نشده')], default=0, verbose_name='وضعیت اصالت'),
        ),
    ]
