# Generated by Django 6.0 on 2026-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auctionvisithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
