# Generated by Django 5.2.9 on 2026-05-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_merge_duplicate_cart_items_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncartitem',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='base_price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='bid_value',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='suggested_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='suggestedprice',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
