# Generated by Django 6.0 on 2026-05-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_alter_auctioncartitem_reserved_amount_and_more'),
        ('store', '0014_material_subject_usage_artwork_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_products', to='store.material'),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_products', to='store.subject'),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_products', to='store.usage'),
        ),
    ]
