# Generated by Django 6.0 on 2026-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auctionproduct_material_auctionproduct_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='price_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات قیمت'),
        ),
    ]
