# Generated by Django 6.0 on 2026-05-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_remove_suggested_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='bid_criteria',
        ),
    ]
