# Generated by Django 5.2.9 on 2026-07-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_add_auctionproduct_lot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionproduct',
            options={'ordering': [models.OrderBy(models.F('lot'), nulls_last=True), 'created_at', 'pk']},
        ),
    ]
