# Generated by Django 6.0 on 2026-07-16 04:47

import django.db.models.deletion
from django.db import migrations, models


def make_artist_nullable(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return

    table_name = 'auction_product'
    column_name = 'artist_id'
    fk_name = 'auction_product_artist_id_82cdd1fe_fk_store_artist_id'

    with connection.cursor() as cursor:
        cursor.execute('SET FOREIGN_KEY_CHECKS = 0')
        try:
            cursor.execute(
                """
                SELECT IS_NULLABLE
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            row = cursor.fetchone()
            is_nullable = row[0] if row else None

            cursor.execute(
                """
                SELECT CONSTRAINT_NAME
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                  AND REFERENCED_TABLE_NAME IS NOT NULL
                """,
                [table_name, column_name],
            )
            existing_fk_names = [fk_row[0] for fk_row in cursor.fetchall()]

            for existing_fk_name in existing_fk_names:
                cursor.execute(
                    f'ALTER TABLE `{table_name}` DROP FOREIGN KEY `{existing_fk_name}`'
                )

            if is_nullable != 'YES':
                cursor.execute(
                    f'ALTER TABLE `{table_name}` MODIFY `{column_name}` integer NULL'
                )

            cursor.execute(
                f'ALTER TABLE `{table_name}` ADD CONSTRAINT `{fk_name}` '
                f'FOREIGN KEY (`{column_name}`) REFERENCES `store_artist` (`id`)'
            )
        finally:
            cursor.execute('SET FOREIGN_KEY_CHECKS = 1')


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_alter_auctionproduct_options'),
        ('store', '0017_alter_artworktype_description_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    make_artist_nullable,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='auctionproduct',
                    name='artist',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auction_products', to='store.artist'),
                ),
            ],
        ),
    ]
