# Generated by Django 5.2.9 on 2026-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_alter_auctionproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='auctionproduct',
            name='uniq_auctionproduct_lot_per_auction',
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='lot',
            field=models.PositiveIntegerField(blank=True, db_column='lot', null=True, verbose_name='شماره لات'),
        ),
    ]
