# Generated by Django 6.0 on 2026-09-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_auction_scheduled_email_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='end_reminder_12h_dispatched_at',
        ),
    ]
