# Generated by Django 6.0 on 2026-09-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0024_remove_auction_end_reminder_12h_dispatched_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionproduct',
            name='bid_value',
        ),
    ]
