# Generated by Django 6.0 on 2026-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0025_remove_auctionproduct_bid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='extended_end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان پایان تمدید شده'),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='extension_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات تمدید'),
        ),
    ]
