# Generated by Django 6.0 on 2026-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_auctionproduct_extended_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='extension_notice_dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیامک تمدید مزایده'),
        ),
    ]
