# Generated by Django 5.2.9 on 2026-09-24 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0027_auction_extension_notice_dispatched_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='شماره فاکتور')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ صدور')),
                ('total_hammer_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع مبالغ چکش\u200cخورده خالص')),
                ('buyers_premium', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حق\u200cالعمل حراج\u200cگزار (۱۰٪)')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل قابل پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='auction.auction', verbose_name='مزایده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_invoices', to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
            ],
            options={
                'verbose_name': 'فاکتور مزایده',
                'verbose_name_plural': 'فاکتورهای مزایده',
                'db_table': 'auction_invoice',
                'ordering': ['-issued_at', '-id'],
                'unique_together': {('auction', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AuctionInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره لات')),
                ('product_code', models.CharField(max_length=64, verbose_name='کد اثر')),
                ('title', models.CharField(max_length=255, verbose_name='نام اثر')),
                ('artist_name', models.CharField(blank=True, max_length=255, verbose_name='نام هنرمند')),
                ('hammer_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت چکش\u200cخورده خالص')),
                ('buyers_premium', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='حق\u200cالعمل حراج\u200cگزار (۱۰٪)')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ کل اثر با احتساب ۱۰٪')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auction.auctioninvoice', verbose_name='فاکتور')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='auction.auctionproduct', verbose_name='اثر')),
            ],
            options={
                'verbose_name': 'قلم فاکتور مزایده',
                'verbose_name_plural': 'اقلام فاکتور مزایده',
                'db_table': 'auction_invoice_item',
                'ordering': ['lot', 'id'],
            },
        ),
    ]
