# Generated by Django 5.2.9 on 2026-09-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0028_auctioninvoice_auctioninvoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioninvoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='auctioninvoiceitem',
            name='artist_name',
        ),
    ]
