# Generated by Django 5.2.9 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_contact_methods",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

