# Generated by Django 5.2.9 on 2026-02-24 08:29

from django.db import migrations, models


def copy_user_names_to_full_name(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")

    qs = CustomUser.objects.all().only("id", "full_name", "first_name", "last_name")
    for user in qs.iterator():
        existing = (getattr(user, "full_name", "") or "").strip()
        if existing:
            continue
        first = (getattr(user, "first_name", "") or "").strip()
        last = (getattr(user, "last_name", "") or "").strip()
        combined = f"{first} {last}".strip()
        if combined:
            CustomUser.objects.filter(id=user.id).update(full_name=combined)


def copy_vr_names_to_full_name(apps, schema_editor):
    VerificationRequest = apps.get_model("accounts", "VerificationRequest")

    qs = VerificationRequest.objects.all().only("id", "full_name", "first_name", "last_name")
    for vr in qs.iterator():
        existing = (getattr(vr, "full_name", "") or "").strip()
        if existing:
            continue
        first = (getattr(vr, "first_name", "") or "").strip()
        last = (getattr(vr, "last_name", "") or "").strip()
        combined = f"{first} {last}".strip()
        if combined:
            VerificationRequest.objects.filter(id=vr.id).update(full_name=combined)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_verified_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.RunPython(copy_user_names_to_full_name, migrations.RunPython.noop),
        migrations.RunPython(copy_vr_names_to_full_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='last_name',
        ),
    ]
