# Generated by Django 5.2.9 on 2026-02-24 08:30

from django.db import migrations


def _create_verification_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    statements = [
        """
        CREATE TRIGGER accounts_vr_sync_user_ai
        AFTER INSERT ON accounts_verificationrequest
        FOR EACH ROW
        UPDATE accounts_customuser
        SET is_verified = NEW.is_verified
        WHERE id = NEW.user_id
        """,
        """
        CREATE TRIGGER accounts_vr_sync_user_au
        AFTER UPDATE ON accounts_verificationrequest
        FOR EACH ROW
        UPDATE accounts_customuser
        SET is_verified = NEW.is_verified
        WHERE id = NEW.user_id
        """,
    ]
    for sql in statements:
        schema_editor.execute(sql)


def _drop_verification_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    statements = [
        "DROP TRIGGER IF EXISTS accounts_vr_sync_user_ai",
        "DROP TRIGGER IF EXISTS accounts_vr_sync_user_au",
    ]
    for sql in statements:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(_create_verification_triggers, _drop_verification_triggers),
    ]
