# Generated by Django 5.2.9 on 2026-02-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                """
                CREATE TRIGGER accounts_vr_sync_user_ai
                AFTER INSERT ON accounts_verificationrequest
                FOR EACH ROW
                UPDATE accounts_customuser
                SET is_verified = NEW.is_verified
                WHERE id = NEW.user_id
                """,
                """
                CREATE TRIGGER accounts_vr_sync_user_au
                AFTER UPDATE ON accounts_verificationrequest
                FOR EACH ROW
                UPDATE accounts_customuser
                SET is_verified = NEW.is_verified
                WHERE id = NEW.user_id
                """,
            ],
            reverse_sql=[
                "DROP TRIGGER IF EXISTS accounts_vr_sync_user_ai",
                "DROP TRIGGER IF EXISTS accounts_vr_sync_user_au",
            ],
        ),
    ]
