# Generated by Django 5.2.9 on 2026-03-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_verification_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='granted_credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
