# Generated by Django 5.2.9 on 2026-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_verification_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='participate_in_auction',
            field=models.BooleanField(default=False, verbose_name='شرکت در مزایده'),
        ),
    ]
