# Generated by Django 5.2.9 on 2026-03-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_participate_in_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='participate_in_auction',
        ),
    ]
