# Generated by Django 5.2.9 on 2026-03-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_credit_verificationrequest_granted_credit'),
        ('accounts', '0008_remove_customuser_participate_in_auction'),
    ]

    operations = [
    ]
