# Generated by Django 5.2.9 on 2026-03-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_creditincreaserequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditIncreaseRequest',
        ),
    ]
