# Generated by Django 5.2.9 on 2026-03-17 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_creditincreaserequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditIncreaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('current_credit', models.DecimalField(decimal_places=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_increase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Increase Request',
                'verbose_name_plural': 'Credit Increase Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
