# Generated by Django 5.2.9 on 2026-03-25 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_creditincreaserequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditincreaserequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Credit Update Log', 'verbose_name_plural': 'Credit Update Logs'},
        ),
        migrations.RemoveField(
            model_name='creditincreaserequest',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='creditincreaserequest',
            name='requested_amount',
        ),
        migrations.RemoveField(
            model_name='creditincreaserequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='creditincreaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='creditincreaserequest',
            name='current_credit',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='اعتبار فعلی (تخصیص یافته)'),
        ),
        migrations.AlterField(
            model_name='creditincreaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='creditincreaserequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
