# Generated by Django 5.2.9 on 2026-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_creditincreaserequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditincreaserequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار بررسی'), (1, 'تایید شده'), (2, 'رد شده')], default=0, verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='creditincreaserequest',
            name='current_credit',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='اعتبار درخواستی/تخصیص یافته'),
        ),
    ]
