# Generated by Django 6.0 on 2026-04-22 05:49

from django.db import migrations, models


def populate_verification_status(apps, schema_editor):
    VerificationRequest = apps.get_model('accounts', 'VerificationRequest')
    VerificationRequest.objects.filter(is_verified=1).update(status=1)
    VerificationRequest.objects.filter(is_verified=0).update(status=0)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_creditincreaserequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار بررسی'), (1, 'تایید شده'), (2, 'رد شده')], default=0, verbose_name='وضعیت درخواست'),
        ),
        migrations.RunPython(populate_verification_status, migrations.RunPython.noop),
    ]
