# Generated by Django 6.0 on 2026-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_verificationrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.RunSQL(
            sql="UPDATE accounts_customuser SET current_credit = credit WHERE current_credit = 0 AND credit > 0",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
