# Generated by Django 5.2.9 on 2026-05-07

from django.db import migrations, models


def _add_missing_previous_credit_columns(apps, schema_editor) -> None:
    table_name = "accounts_creditincreaserequest"
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
        existing_columns = {col.name for col in description}

    statements = []
    if "previous_current_credit" not in existing_columns:
        statements.append(
            "ALTER TABLE `accounts_creditincreaserequest` "
            "ADD COLUMN `previous_current_credit` DECIMAL(15, 0) NOT NULL DEFAULT 0"
        )
    if "previous_total_credit" not in existing_columns:
        statements.append(
            "ALTER TABLE `accounts_creditincreaserequest` "
            "ADD COLUMN `previous_total_credit` DECIMAL(15, 0) NOT NULL DEFAULT 0"
        )

    for sql in statements:
        schema_editor.execute(sql)


def _noop_reverse(apps, schema_editor) -> None:
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_customuser_current_credit"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_missing_previous_credit_columns, _noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="creditincreaserequest",
                    name="previous_current_credit",
                    field=models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        default=0,
                        editable=False,
                    ),
                ),
                migrations.AddField(
                    model_name="creditincreaserequest",
                    name="previous_total_credit",
                    field=models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        default=0,
                        editable=False,
                    ),
                ),
            ],
        ),
    ]

