# Generated by Django 5.2.9 on 2026-05-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_creditincreaserequest_previous_credit_fields"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "DROP TRIGGER IF EXISTS update_user_credit_after_insert",
                "DROP TRIGGER IF EXISTS update_user_credit_after_update",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]

