# Generated by Django 5.2.9 on 2026-05-07

from django.db import migrations


def _drop_credit_request_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return

    statements = [
        "DROP TRIGGER IF EXISTS update_user_credit_after_insert",
        "DROP TRIGGER IF EXISTS update_user_credit_after_update",
    ]
    for sql in statements:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_creditincreaserequest_previous_credit_fields"),
    ]

    operations = [
        migrations.RunPython(_drop_credit_request_triggers, migrations.RunPython.noop),
    ]

