# Generated by Django 5.2.9 on 2026-07-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_emailverificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_contact_methods',
            field=models.JSONField(blank=True, default=list, help_text='کانال\u200cهای ارتباطی فعال کاربر برای دریافت اطلاعیه\u200cها (ایمیل، پیامک، تلگرام)', verbose_name='تنظیمات کانال\u200cهای دریافت پیام'),
        ),
    ]
