# Generated by Django 5.2.9 on 2026-09-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_customuser_is_sms_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationotp',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
